### ISSUE TITLE
Resolve unintentional MIT License omission

### ISSUE THREAD

**Issue by Josverl** [paulober/Pico-W-Stub#11]
Hi Paul,

It appears that the subs in this repo are either:
- copies of the stubs in https://github.com/Josverl/micropython-stubs
- generated by the use of the micropython-stubber tool : https://github.com/Josverl/micropython-stubbber

That in itself is not a problem at all, happy that you have been able to use them for the exact purpose that I have built these for.
However both are released under [MIT licence](https://github.com/Josverl/micropython-stubs/blob/main/LICENSE.md) which requires that that license is respected. 
The relevant parts: 
``` 
MIT License

Copyright (c) 2020-2023 Jos Verlinde

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software and stubs.
```
So it is no problem that you place this under a different license, however you cannot remove the earlier license and notice.
in the development and publication of the micropython-stubs that have used as the base, I have taken specific effort to respect , and where relevant copy over relevant licenses with the stubs.

I kindly ask you to do the same.

Regards,
Jos Verlinde

**Comment by paulober** [comment]
@Josverl I'm sorry that I missed that one and of course I'll add the license header to the stubber which seems to be missing in the minified copy I got from your repo some months ago.

The repo does not contain copies of your stubs repo but it contains the auto-generated ones from the stubber and were than each one hand modified.

I also thought about in the past to maybe close this repo and contact you if it would be possible to incorporate your stubs into the [MicroPico](https://github.com/paulober/MicroPico) extension. In return I would to my contributions back to your stubs repo instead of this one.
My only problem was that your repo is quite big and contains many different stubs for the pico-w. Also most of them don't contain the parameters for functions and doc-strings for classes and methods or maybe I haven't found them.

**Comment by Josverl** [comment]
Paul, 
thanks for resolving this.

really appreciated.
Regards,
Jos Verlinde

**Comment by paulober** [comment]
Jos,
sounds great. I thought about making the extension more suitable for different boards so giving the user the option to chose between pico, pico-w and other stubs would be a great step towards the right direction.

> If you agree, then I'll let him know and see how we can work together on this.

Sure

**Comment by Josverl** [comment]
OK I'll ping Jim on discord. Do you have a discord handle?

**Comment by paulober** [comment]
> OK I'll ping Jim on discord. Do you have a discord handle?

Yes: paulober

**Comment by Josverl** [comment]
I've let him know, but he has not responded so far
